.Dd 6/10/14
.Dt gat 1
.Os NetBSD
.Sh NAME
.Nm gat
.Nd GTK+ ACPI Tray Battery Monitor
.Sh SYNOPSIS
.Nm
.Ar devname
.Sh DESCRIPTION
.Nm
is a GTK+ based utility for monitoring battery status from any window manager that has a
system tray capable of containing GTK+ system tray icons. GTK+-3.0 was chosen because it is
compatible with most window managers, and already contains all of the necessary icon assets 
for all of the battery states reflected by gat.
.Pp
.Nm
is intended to be used on machines that do not have apm, as an alternative to other
(more portable) apm-based solutions.
.Pp
It is also worth noting, that due to the nature of ACPI,
.Nm
must poll the status of the device, and does so once every two seconds. Charging status is
also unrelated to external power sources, but is instead only an indication of charging
versus discharging. Because of this, the tray icon may indicate that a battery is full, and
not charging, while plugged in. This is normal, and merely indicates that no positive
charging of the battery is happening.
.Sh EXAMPLES
Invoke
.Nm
with the device name you want it to monitor as the sole argument. For example:
.Pp
$
.Nm
acpibat0 &
.Pp
This will spawn an instance of
.Nm
into your system tray with the status of that device displayed.
If you have more than one battery to monitor, just invoke
.Nm
with an argument for each device.
.Pp
To quit a running instance of
.Nm ,
simply click on the tray icon and select the ``Quit'' menu item.
.Sh SEE ALSO 
.Xr envstat 8 , 
.Xr envsys 4
.Sh AUTHORS
.Nm
was written by Daniel Loffgren. 
